spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.gary.assistant: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

gary:
  scraper:
    amazon:
      rate-limit: 5
    mercadolivre:
      rate-limit: 5
